services:
  - type: web
    name: landmark-backend
    runtime: python
    buildCommand: pip install --no-cache-dir -r requirements.txt && chmod +x start.sh
    startCommand: bash start.sh
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
